# Generated by Django 3.0.3 on 2020-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_auto_20200609_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
